# Generated by Django 3.0.2 on 2020-02-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='username',
        ),
    ]
