# Generated by Django 3.0.2 on 2020-03-02 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0002_password_update01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doggo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
                ('age', models.IntegerField(blank=True)),
                ('description', models.CharField(max_length=500)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('average_rating', models.IntegerField(default=0)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(default=0)),
                ('rated_doggo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_app.Doggo')),
                ('user_who_voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
