# Generated by Django 3.0.2 on 2020-02-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0005_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
