# Generated by Django 3.0.2 on 2020-02-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0006_auto_20200210_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(help_text='YYYY'),
        ),
    ]
