# Generated by Django 3.0.2 on 2020-02-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0007_auto_20200212_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
