# Generated by Django 3.0.2 on 2020-02-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0008_user_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
