# Generated by Django 3.0.2 on 2020-02-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0009_auto_20200212_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
