# Generated by Django 3.0.2 on 2020-02-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0011_auto_20200212_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='blah123', max_length=50),
        ),
    ]
